### ISSUE TITLE
0.8.1 crashes frequently on Mac

### ISSUE THREAD

**Issue by mstahv** [OpenOrienteering/mapper#1077]
### Steps to reproduce
1. Open ocad file
2. Save in mapper format

### Actual behaviour
Crash

### Expected behaviour
Saved file

### Configuration
Mapper Version: 0.8.1
Operating System: Mac

Works fine with 0.8.0. 

I can share the OCD file I used privately if needed (didn't test with other files).

**Comment by dg0yt** [comment]
This doesn't happen with my test files. Please send the file, or ask for an private upload link via e-mail.

**Comment by mstahv** [comment]
In you email, let me know if you need more help to see what is going on!

**Comment by dg0yt** [comment]
Save the file in Mapper format didn't crash here in 0.8.1/Linux. I will need more time or information.

**Comment by mstahv** [comment]
Here is the crash report if it helps. First nothing happens, but the file is not written, then when you try to do something after saving, the app dies.

[crash_report.txt](https://github.com/OpenOrienteering/mapper/files/1814271/crash_report.txt)

**Comment by mstahv** [comment]
It (the 0.8.1 version) actually seems to crash on almost all actions. Tried creating a new ISOM 2017 map and draw a curve.

[crash_report.txt](https://github.com/OpenOrienteering/mapper/files/1814293/crash_report.txt)

**Comment by mstahv** [comment]
Yes, I use English as my main language on all software.

**Comment by mstahv** [comment]
Are there any log files I could send to you? Do you know if it is it hard to set up the development environment for Mac? I haven't done any C++ development since university studies, but maybe I could help on this some evening.

**Comment by dg0yt** [comment]
I was able to reproduce crashes with the released 0.8.1 DMG _when saving files_ (i.e. not on all actions), but not yet in my development environment.

The first crash report wasn't useful but is what I can reproduce.

The second crash report is from inside [mapper code](https://github.com/OpenOrienteering/mapper/blob/276a401010277eba13f53ef133a41cacce4189a3/src/tools/draw_path_tool.cpp#L682) indeed, but unrelated to your test file IIUC, and probably unrelated to saving?

At the moment, I have no idea what is wrong in the [changes between 0.8.0 and 0.8.1](https://github.com/OpenOrienteering/mapper/compare/v0.8.0...v0.8.1).

Setting up the environment means dealing with the third-party components. I made it easy to reproduce release builds (building everything from source) with the Superbuild project. The superbuild can also be used to do debug builds and even development, by importing the openorienteering-mapper source and build directories in Qt Creator. And if you start with Qt Creator and the Qt version it includes, the superbuild doesn't need to recompile Qt. But the closer to the end of this paragraph, the less documenation you will find.

**Comment by mstahv** [comment]
Correct, with the second crash I didn't even try to save the file yet. Something odd in the Mac build at least. Just let me know if want me to try some debug build. Thanks in advance, keep up the good work!

**Comment by dg0yt** [comment]
I could always need more help and time... But for this issue, there is the complication that the crash doesn't occur in the development environment or other platforms. To track it down, it is probably neccessary to do release-type builds. 
- [ ] First we should compare the files inside the 0.8.0 and 0.8.1 DMG. Only Mapper and translations should have changed: In my release build environment, only the Mapper source code should have been rebuild for v0.8.1, but not the unchanged third party components. This is something you could do as well as I can.
- [ ] Next, I will just rebuild v0.8.1, in case we hit some random bit defect.
- [ ] Next, I would bisect the changes from v0.8.0 to 0.8.1.

**Comment by dg0yt** [comment]
Fixed in release v0.8.1.1.

**Comment by mstahv** [comment]
This may be another issue (or a build issue? My version number still shows 0.8.1 although I install form 0.8.1.1 dmg), but drawing a contour on new map still brings Mapper down for me.


![mapper mac bug](https://user-images.githubusercontent.com/1478052/37511802-cff70036-2908-11e8-987a-bffd91a90d9b.gif)

[crash_report.txt](https://github.com/OpenOrienteering/mapper/files/1818543/crash_report.txt)

**Comment by dg0yt** [comment]
Matti, I verified the 0.8.1.1 DMG download on two computers now: No more crashes, and the "About OpenOrienteering Mapper" dialog shows 0.8.1.1. (Only Finder still shows 0.8.1 in the window title of the opened DMG.)

**Comment by dg0yt** [comment]
Please test v0.8.1.2.
